server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shopping?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/page/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false

#日记
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis:
  type-aliases-package: com.broken.shopbackend.domain